services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - redis-data:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=admin1234

volumes:
  pgdata:
  redis-data:

