import { AuthProvider } from './context/AuthContext';
import type { Metadata } from 'next';
import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Zoomerang',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased flex flex-col bg-gradient-to-r from-blue-500 via-purple-600 to-pink-600 h-screen`}>
        <AuthProvider>
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
